package uz.hayatbank.api.utils;

public interface ReturnCodes {
    int CONST_DB_ERROR = -1;
    int CONST_SUCCESS = 0;
    int CONST_PHONE_IS_EMPTY = 1;
    int CONST_CONTENT_IS_EMPTY = 2;
    int CONST_INCORRECT_PHONE_NUMBER = 3;
    int CONST_REQUIRED_FIELD_EMPTY = 4;
    int CONST_CONFIRMATION_CODE_EMPTY = 5;
    int CONST_INPUT_CORRECT_CONFIRMATION_CODE = 6;
    int CONST_GET_CONFIRMATION_CODE_AGAIN = 7;
    int CONST_CONFIRMATION_CODE_LIMIT_EXCEEDED = 8;
    int CONST_CONFIRMATION_CODE_EXPIRED = 9;
    int CONST_FIO_IS_EMPTY = 10;
    int CONST_USER_NOT_FOUND = 11;
    int CONST_INVALID_AMOUNT = 12;
    int CONST_PAYMENT_DETAIL_IS_EMPTY = 13;
    int CONST_NOT_ENOUGH_MONEY = 14;
    int CONST_INVALID_PHONE_NUMBER = 15;
    int CONST_INVALID_EMAIL = 16;
    int CONST_PHONE_EXISTS = 17;
    int CONST_INVALID_DATE_FORMAT = 18;
}
